/// action_setting_color_reset()

if(current_hour < 18 && current_hour > 6){
	action_setting_color_interface(c_main)
	action_setting_color_text(c_text)
	action_setting_color_tips(c_tips)
	action_setting_color_tips_text(c_white)
	action_setting_color_buttons(c_secondary)
	action_setting_color_buttons_text(c_white)
	action_setting_color_timeline(c_white)
	action_setting_color_timeline_text(c_text)
	action_setting_color_timeline_marks(c_secondary)
	action_setting_color_timeline_select_box(c_blue)
	action_setting_color_boxes(c_white)
	action_setting_color_boxes_text(c_text)
}
else{
	action_setting_color_interface(c_main_dark)
	action_setting_color_text(c_text_dark)
	action_setting_color_tips(c_text_dark)
	action_setting_color_tips_text(c_main_dark)
	action_setting_color_buttons(c_secondary_dark)
	action_setting_color_buttons_text(c_white)
	action_setting_color_timeline(c_main_dark)
	action_setting_color_timeline_text(c_text_dark)
	action_setting_color_timeline_marks(c_secondary_dark)
	action_setting_color_timeline_select_box(c_secondary_dark)
	action_setting_color_boxes(color_add_value(c_gray, -40))
	action_setting_color_boxes_text(c_text_dark)
}

action_setting_color_highlight(c_highlight)
action_setting_color_highlight_text(c_white)
action_setting_color_alerts(c_alerts)
action_setting_color_alerts_text(c_text)
action_setting_color_viewport_selection(c_white)